"""actualizar password Modelo BD

Revision ID: 541af2c8b27a
Revises: 
Create Date: 2023-09-04 15:12:52.885543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "541af2c8b27a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=250), nullable=True)
        )
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.VARCHAR(length=250), nullable=False)
        )
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
